#!/bin/bash
#Read file and convert HEX epoch to date and print
awk --posix '{if($1 ~ /^([0-9A-F]){8}$/){"date --rfc-3339=seconds -d $(echo @$((0x" $1 ")))"|getline d;print "["d"] "$0}else print "["d"]          "$0}' "$@"
