#!/bin/bash
# clean up after test

irm(){	# interactive deletion
	local -r t="$1";shift
	{ echo "$t";find "$@";} | more
	local r;read -n1 -s -p 'Deleting output files? [y/N] ' r
	if [[ $r == y ]];then find "$@" -delete;echo "Done.";else echo "Skip deletion.";fi
}

irm '### RUN files ###' ../jobs/*/run -type f
irm '### OUT files ###' ../jobs/*/out -type f
irm '### WORK files ###' ../work -type f
irm '### WORK dirs ###' ../work -maxdepth 1 -mindepth 1 -type d
