#!/bin/bash
# Run test
f(){ while read;do printf '[%s] %s\n' "$1" "$REPLY";done;}

{ { { ./testing.mira 0 4096 P-4096-0 $((40+$(date +%s))) 2>&1 1>&3 3>&- | f 0e;} 3>&1 1>&2 | f 0o &
    { ./testing.mira 1 8192 P-8192-0 $((40+$(date +%s))) MEASURE 2>&1 1>&3 3>&- | f 1e;} 3>&1 1>&2 | f 1o &
    { ./testing.mira 2 8192 P-8192-1 $((40+$(date +%s))) HMC 2>&1 1>&3 3>&- | f 2e;} 3>&1 1>&2 | f 2o &
   wait
} 2>&1 1>&3 3>&- | tee ../work/test.stderr;} 3>&1 1>&2 | tee ../work/test.stdout
